### ISSUE TITLE
on macOS

### ISSUE THREAD

**Issue by t-cool** [t-sin/niko#3]
I'm setting up niko, but I face with the following error:

```
$ APP_ENV=production qlot exec clackup app.lisp --server woo --debug nil --address 127.0.0.1 --port 8080 --worker-num 4
Woo server is going to start.
Listening on localhost:8080.
Unhandled WOO.EV.CONDITION:OS-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                 {10005505B3}>:
  Cannot bind fd to the address "127.0.0.1" (Code: 48)

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10005505B3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<WOO.EV.CONDITION:OS-ERROR {100217FC63}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<WOO.EV.CONDITION:OS-ERROR {100217FC63}>)
```

```
$ qlot exec lake server

> niko@0.1.0 dev-server /Users/noguchihiroki/Desktop/niko-master
> webpack-dev-server --config ./config/webpack.config.js

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! niko@0.1.0 dev-server: `webpack-dev-server --config ./config/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the niko@0.1.0 dev-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/noguchihiroki/.npm/_logs/2018-05-05T02_32_55_208Z-debug.log
Unhandled UIOP/RUN-PROGRAM:SUBPROCESS-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                                         {1007437A13}>:
  Subprocess #<UIOP/LAUNCH-PROGRAM::PROCESS-INFO {100750AB83}>
 with command ("npm" "run" "dev-server")
 exited with error code 1

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1007437A13}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {1001E881A3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {1001E881A3}>)
```

**Comment by t-cool** [comment]
I killed the ps on 8080 and I solved the issue.
